- hosts: localhost
  tasks:
    - name: Show facts
      debug: msg="{{ ansible_distribution }}"
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/arch.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/dev.yml
    - import_tasks: tasks/displaylink.yml
    - import_tasks: tasks/displaymanager.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/productivity.yml
    - import_tasks: tasks/gtk.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/sci.yml
    - import_tasks: tasks/x/displays.yml
