- hosts: localhost
  tasks:
    - name: Show facts
      debug: msg="{{ ansible_distribution }}"
    - include: tasks/core.yml
    - include: tasks/arch.yml
    - include: tasks/ssh.yml
    - include: tasks/terminal.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml
    - include: tasks/dev.yml
    - include: tasks/i3.yml
    - include: tasks/gnome.yml
    - include: tasks/gtk.yml
    - include: tasks/gui.yml
    - include: tasks/fonts.yml
