- hosts: localhost
  pre_tasks:
    - name: "Update pacman"
      become: true
      when: ansible_distribution == "Manjaro"
      community.general.pacman:
        update_cache: true
    - name: "Update apt"
      become: true
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/terminal.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml
