- name: Install golang
  tags:
    - dev
  become: yes
  ansible.builtin.unarchive:
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
    src: https://go.dev/dl/go1.19.linux-amd64.tar.gz
