- name: Install base
  tags:
    - core
  when: ansible_distribution != "MacOSX"
  become: true
  package: name=base-devel state=latest

- name: Install make
  tags:
    - core
  when: ansible_distribution != "MacOSX"
  become: true
  package: name=make state=latest
