- name: Golang
  tags:
    - dev
  include_tasks: dev/go.yml
- name: Js
  tags:
    - dev
  include_tasks: dev/js.yml
- name: Python
  tags:
    - dev
  include_tasks: dev/python.yml
- name: Dotnet
  tags:
    - dev
  include_tasks: dev/dotnet.yml
- name: Haskell
  tags:
    - dev
  include_tasks: dev/haskell.yml
