- name: Get dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:rhermens/dotfiles.git'
    dest: "{{lookup('env', 'HOME')}}/dotfiles"
    recursive: yes
    accept_hostkey: yes
    version: master
- name: Run dotbot
  shell: cd $HOME/dotfiles && ./install

