- name: Create fonts directory
  tags:
    - fonts
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    state: directory

- name: Install Source Code Pro Mono
  tags:
    - fonts
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/SourceCodePro.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
