- name: Clone Tokyonight GTK
  tags:
    - gtk
  ansible.builtin.git:
    repo: 'git@github.com:Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git'
    dest: "{{lookup('env', 'HOME')}}/.gtk-tokyonight"
    recursive: yes
    accept_hostkey: yes
    version: master

- name: Create themes directory
  tags:
    - gtk
  file:
    path: "{{lookup('env', 'HOME')}}/.themes"
    state: directory

- name: Link Tokyonight GTK
  tags:
    - gtk
  become: yes
  ansible.builtin.shell:
    cmd: ln -s "{{lookup('env', 'HOME')}}/.gtk-tokyonight/themes/Tokyonight-Dark-BL" "/usr/share/themes/Tokyonight-Dark-BL"
    creates: "/usr/share/themes/Tokyonight-Dark-BL/index.theme"

- name: Link Tokyonight GTK Icons
  tags:
    - gtk
  become: yes
  ansible.builtin.shell:
    cmd: ln -s "{{lookup('env', 'HOME')}}/.gtk-tokyonight/icons/Tokyonight-Dark" "/usr/share/icons/Tokyonight-Dark"
    creates: "/usr/share/icons/Tokyonight-Dark/index.theme"

- name: Install qt5-styleplugins
  tags:
    - gtk
  yay: name=qt5-styleplugins state=latest

- name: Install GTK2 engines
  tags:
    - gtk
  become: yes
  package: name=gtk-engines state=latest

- name: Install Murrine Engine 
  tags:
    - gtk
  become: yes
  package: name=gtk-engine-murrine state=latest

- name: Install Gnome themes extra
  tags:
    - gtk
  become: yes
  package: name=gnome-themes-extra state=latest

- name: Link Configuration
  tags:
    - gtk
  become: yes
  ansible.builtin.shell:
    cmd: ln -s "{{lookup('env', 'HOME')}}/dotfiles/gtk/settings.ini" "/etc/gtk-3.0/settings.ini"
    creates: "/etc/gtk-3.0/settings.ini"
