- name: Clone Tokyonight GTK
  tags:
    - gtk
  ansible.builtin.git:
    repo: 'git@github.com:Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git'
    dest: "{{lookup('env', 'HOME')}}/.gtk-tokyonight"
    recursive: yes
    accept_hostkey: yes
    version: master

- name: Create themes directory
  tags:
    - gtk
  file:
    path: "{{lookup('env', 'HOME')}}/.themes"
    state: directory

- name: Link Tokyonight GTK
  tags:
    - gtk
  ansible.builtin.shell:
    cmd: ln -s "{{lookup('env', 'HOME')}}/.gtk-tokyonight/themes/Tokyonight-Dark-B-LB" "{{lookup('env', 'HOME')}}/.themes/Tokyonight-Dark-B-LB"
    creates: "{{lookup('env', 'HOME')}}/.themes/Tokyonight-Dark-B-LB/index.theme"
