- name: Install alacritty
  tags:
    - gui
  become: true
  package: name=alacritty state=latest

- name: Clone st
  tags:
    - gui
  ansible.builtin.git:
    repo: 'git@github.com:rhermens/st.git'
    dest: "{{lookup('env', 'HOME')}}/st"
    accept_hostkey: yes
    version: master

- name: Install st
  tags:
    - gui
  become: true
  ansible.builtin.shell:
    cmd: "cd {{lookup('env', 'HOME')}}/st; makepkg --force --clean --install"
    creates: "/usr/bin/st"

