
- name: Ubuntu package facts
  tags: 
    - terminal
    - nvim
  set_fact:
    pyvenv: "python3-venv"
  when: ansible_distribution == "Ubuntu"
- name: Manjaro package facts
  tags: 
    - nvim
    - terminal
  set_fact:
    pyvenv: "python-virtualenv"
  when: ansible_distribution == "Archlinux"

- name: nvim repository
  tags:
    - terminal
    - nvim
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install nvim
  tags:
    - terminal
    - nvim
  become: true
  package: name=neovim state=latest

- name: Install py-venv (CHADTree dep)
  tags:
    - terminal
    - nvim
  become: true
  package: name={{pyvenv}} state=latest

- name: Get packer
  tags:
    - nvim
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    accept_hostkey: yes
    depth: 1

