- name: nvim repository
  tags:
    - terminal
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install nvim
  tags:
    - terminal
  become: yes
  package: name=neovim state=latest

- name: Install py-venv
  tags:
    - terminal
  become: yes
  package: name=python3-venv state=latest

- name: "Plugged Directory"
  tags:
    - terminal
  file:
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload"
    mode: 0700
    state: directory
- name: Plugged
  tags:
    - terminal
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload/plug.vim"
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload/plug.vim"

- name: "PlugInstall"
  tags:
    - terminal
    - config
  ansible.builtin.shell:
    cmd: nvim --headless +PlugInstall +qa
