
- name: Ubuntu package facts
  tags: 
    - terminal
  set_fact:
    pyvenv: "python3-venv"
  when: ansible_distribution == "Ubuntu"
- name: Manjaro package facts
  tags: 
    - terminal
  set_fact:
    pyvenv: "python-virtualenv"
  when: ansible_distribution == "Archlinux"

- name: nvim repository
  tags:
    - terminal
    - nvim
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install nvim
  tags:
    - terminal
    - nvim
  become: true
  package: name=neovim state=latest

- name: Install py-venv
  tags:
    - terminal
    - nvim
  become: true
  package: name={{pyvenv}} state=latest

- name: "Plugged Directory"
  tags:
    - terminal
    - nvim
  file:
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload"
    mode: 0700
    state: directory
- name: Plugged
  tags:
    - terminal
    - nvim
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload/plug.vim"
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/autoload/plug.vim"

- name: "PlugInstall"
  tags:
    - terminal
    - config
    - nvim
  ansible.builtin.shell:
    cmd: nvim --headless +PlugInstall +qa
    creates: "{{lookup('env', 'HOME')}}/.local/shared/nvim/plugged/"
