
- name: nvim repository
  tags:
    - nvim
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install nvim
  tags:
    - nvim
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  package: name=neovim state=latest

- name: Get packer
  tags:
    - nvim
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{lookup('env', 'HOME')}}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    accept_hostkey: yes
    depth: 1

