- name: "SSH Directory"
  tags:
    - ssh
  file:
    dest: "{{lookup('env', 'HOME')}}/.ssh"
    mode: 0700
    state: directory
- name: "Copy ssh keys"
  tags:
    - ssh
  copy:
    src: "./.ssh/id_ed25519"
    dest: "{{lookup('env', 'HOME')}}/.ssh/id_ed25519"
    mode: 0600
- name: "Copy pub ssh keys"
  tags:
    - ssh
  copy:
    src: "./.ssh/id_ed25519.pub"
    dest: "{{lookup('env', 'HOME')}}/.ssh/id_ed25519.pub"
    mode: 0644
