- name: Install zsh
  when: ansible_distribution != "MacOSX"
  tags:
    - terminal
    - zsh  
  become: true
  package: name=zsh state=latest

- name: Antigen
  tags:
    - terminal
    - zsh  
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "{{lookup('env', 'HOME')}}/antigen"
    accept_hostkey: yes
    version: master

- name: Install tmux
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  package: name=tmux state=latest

- name: Install tldr
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  package: name=tldr state=latest

- name: Install fzf
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  package: name=fzf state=latest

- name: Install ripgrep
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  tags:
    - terminal
  package: name=ripgrep state=latest

- name: Install fd
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  tags:
    - terminal
  package: name=fd state=latest

- name: Set shell
  when: ansible_distribution != "MacOSX"
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  user:
    name: roy
    shell: /usr/bin/zsh

- name: p10k
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:romkatv/powerlevel10k.git'
    dest: "{{lookup('env', 'HOME')}}/powerlevel10k"
    depth: 1
    accept_hostkey: yes
    version: master

- name: Install kitty
  tags:
    - gui
    - terminal
  become: yes
  package: name=kitty state=latest

