- name: Install zsh
  tags:
    - terminal
  become: yes
  package: name=zsh state=latest

- name: "Zsh hightlighting"
  tags:
    - terminal
  become: yes
  package: name=zsh-syntax-highlighting state=latest

- name: Install tmux
  tags:
    - terminal
  become: yes
  package: name=tmux state=latest

- name: Clone fzf
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:junegunn/fzf.git'
    dest: "{{lookup('env', 'HOME')}}/.fzf"
    accept_hostkey: yes
    version: master

- name: Install fzf
  tags:
    - terminal
  become: yes
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/bin/"
    dest: /usr/local/bin
    mode: 0755

- name: Fzf zsh binding
  tags:
    - terminal
  become: yes
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/shell/"
    dest: /usr/share/fzf

- name: Install ripgrep
  tags:
    - terminal
  become: yes
  package: name=ripgrep state=latest

- name: Set shell
  tags:
    - terminal
  become: yes
  user:
    name: roy
    shell: /usr/bin/zsh

- name: p10k
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:romkatv/powerlevel10k.git'
    dest: "{{lookup('env', 'HOME')}}/powerlevel10k"
    depth: 1
    accept_hostkey: yes
    version: master

