- name: Install zsh
  when: ansible_distribution != "MacOSX"
  tags:
    - terminal
    - zsh  
  become: true
  package: name=zsh state=latest

- name: Antigen
  tags:
    - terminal
    - zsh  
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "{{lookup('env', 'HOME')}}/antigen"
    accept_hostkey: yes
    version: master

- name: Install tmux
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  package: name=tmux state=latest

- name: Clone fzf
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:junegunn/fzf.git'
    dest: "{{lookup('env', 'HOME')}}/.fzf"
    accept_hostkey: yes
    version: master

- name: Setup fzf
  tags:
    - terminal
  shell: 
    cmd: cd $HOME/.fzf && ./install --bin
    creates: "{{lookup('env', 'HOME')}}/.fzf/bin/fzf"

- name: Install fzf
  tags:
    - terminal
  become: true
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/bin/"
    dest: /usr/local/bin
    mode: 0755

- name: Fzf zsh binding
  tags:
    - terminal
  become: true
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/shell/"
    dest: /usr/local/share/fzf

- name: Install ripgrep
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  tags:
    - terminal
  package: name=ripgrep state=latest

- name: Install fd
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  tags:
    - terminal
  package: name=fd state=latest

- name: Set shell
  when: ansible_distribution != "MacOSX"
  tags:
    - terminal
  become: "{{ ansible_distribution != \"MacOSX\" }}"
  user:
    name: roy
    shell: /usr/bin/zsh

- name: p10k
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:romkatv/powerlevel10k.git'
    dest: "{{lookup('env', 'HOME')}}/powerlevel10k"
    depth: 1
    accept_hostkey: yes
    version: master

