- name: Clone st
  tags:
    - gui
  ansible.builtin.git:
    repo: 'git@github.com:rhermens/st.git'
    dest: "{{lookup('env', 'HOME')}}/st"
    accept_hostkey: yes
    version: master

- name: Install st
  tags:
    - gui
  become: true
  ansible.builtin.shell:
    cmd: "cd {{lookup('env', 'HOME')}}/st; makepkg --force --clean --install"
    creates: "/usr/bin/st"

- name: Install zsh
  tags:
    - terminal
    - zsh  
  become: true
  package: name=zsh state=latest

- name: Antigen
  tags:
    - terminal
    - zsh  
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "{{lookup('env', 'HOME')}}/antigen"
    accept_hostkey: yes
    version: master

- name: Install ranger
  tags:
    - terminal
  become: true
  package: name=ranger state=latest

- name: Install tmux
  tags:
    - terminal
  become: true
  package: name=tmux state=latest

- name: Clone fzf
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:junegunn/fzf.git'
    dest: "{{lookup('env', 'HOME')}}/.fzf"
    accept_hostkey: yes
    version: master

- name: Setup fzf
  tags:
    - terminal
  shell: 
    cmd: cd $HOME/.fzf && ./install --bin
    creates: "{{lookup('env', 'HOME')}}/.fzf/bin/fzf"

- name: Install fzf
  tags:
    - terminal
  become: true
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/bin/"
    dest: /usr/local/bin
    mode: 0755

- name: Fzf zsh binding
  tags:
    - terminal
  become: true
  ansible.builtin.copy:
    src: "{{lookup('env', 'HOME')}}/.fzf/shell/"
    dest: /usr/share/fzf

- name: Install ripgrep
  tags:
    - terminal
  become: true
  package: name=ripgrep state=latest

- name: Install fd
  tags:
    - terminal
  become: true
  package: name=fd state=latest

- name: Set shell
  tags:
    - terminal
  become: true
  user:
    name: roy
    shell: /usr/bin/zsh

- name: p10k
  tags:
    - terminal
  ansible.builtin.git:
    repo: 'git@github.com:romkatv/powerlevel10k.git'
    dest: "{{lookup('env', 'HOME')}}/powerlevel10k"
    depth: 1
    accept_hostkey: yes
    version: master


